# This file will only be used for quick local development
# Kubernetes will be used in production
services:
  mysql-rp-businessentity:
    image: mysql:latest
    container_name: mysql-rp-businessentity
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: RPBusinessEntityDB
    ports:
      - "3307:3306"
    volumes:
      - ./deploy/businessEntity.init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_businessentity_vol:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s
    networks:
      - retailpulse-network

  rp-businessentity-app:
    image: rp-businessentity-app:v0.1.0
    container_name: app-rp-businessentity
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-rp-businessentity:3306/RPBusinessEntityDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SERVER_PORT: 8082
      AUTH_SERVER_URL: http://app-iam:8081
    ports:
      - "8082:8082"
    depends_on:
      mysql-rp-businessentity:
        condition: service_healthy
      # app-iam:
      #   condition: service_started
    networks:
      - retailpulse-network

networks:
  retailpulse-network:
    driver: bridge

volumes:
  mysql_businessentity_vol:

